/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TripType = IDL.Variant({
  'round' : IDL.Null,
  'oneway' : IDL.Null,
});
export const RideStatus = IDL.Variant({
  'requested' : IDL.Null,
  'cancelled' : IDL.Null,
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Ride = IDL.Record({
  'id' : IDL.Nat,
  'status' : RideStatus,
  'destination' : IDL.Text,
  'tripType' : TripType,
  'fare' : IDL.Nat,
  'user' : IDL.Principal,
  'pickup' : IDL.Text,
  'driver' : IDL.Opt(IDL.Principal),
});
export const MaintenanceAlert = IDL.Record({
  'owner' : IDL.Principal,
  'vehicleNumber' : IDL.Text,
  'issue' : IDL.Text,
});
export const Vehicle = IDL.Record({
  'model' : IDL.Text,
  'ownerName' : IDL.Text,
  'owner' : IDL.Principal,
  'make' : IDL.Text,
  'number' : IDL.Text,
  'driver' : IDL.Opt(IDL.Principal),
});
export const UserProfile = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const FraudAlert = IDL.Record({
  'rideId' : IDL.Nat,
  'details' : IDL.Text,
});
export const DriverProfile = IDL.Record({
  'name' : IDL.Text,
  'earnings' : IDL.Nat,
  'vehicle' : IDL.Text,
  'phone' : IDL.Text,
  'online' : IDL.Bool,
});
export const PlatformStats = IDL.Record({
  'totalTrips' : IDL.Nat,
  'activeDrivers' : IDL.Nat,
  'fraudAlerts' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRide' : IDL.Func([IDL.Nat], [], []),
  'addFraudAlert' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addMaintenanceAlert' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDriverToVehicle' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'bookRide' : IDL.Func([IDL.Text, IDL.Text, TripType, IDL.Nat], [IDL.Nat], []),
  'getActiveTrips' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'getAllMaintenanceAlerts' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceAlert)],
      ['query'],
    ),
  'getAllRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriverEarnings' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getFraudAlerts' : IDL.Func([], [IDL.Vec(FraudAlert)], ['query']),
  'getOnlineDrivers' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getRideById' : IDL.Func([IDL.Nat], [IDL.Opt(Ride)], ['query']),
  'getRidesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Ride)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerDriver' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleOnlineStatus' : IDL.Func([], [], []),
  'updateRideStatus' : IDL.Func([IDL.Nat, RideStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TripType = IDL.Variant({ 'round' : IDL.Null, 'oneway' : IDL.Null });
  const RideStatus = IDL.Variant({
    'requested' : IDL.Null,
    'cancelled' : IDL.Null,
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Ride = IDL.Record({
    'id' : IDL.Nat,
    'status' : RideStatus,
    'destination' : IDL.Text,
    'tripType' : TripType,
    'fare' : IDL.Nat,
    'user' : IDL.Principal,
    'pickup' : IDL.Text,
    'driver' : IDL.Opt(IDL.Principal),
  });
  const MaintenanceAlert = IDL.Record({
    'owner' : IDL.Principal,
    'vehicleNumber' : IDL.Text,
    'issue' : IDL.Text,
  });
  const Vehicle = IDL.Record({
    'model' : IDL.Text,
    'ownerName' : IDL.Text,
    'owner' : IDL.Principal,
    'make' : IDL.Text,
    'number' : IDL.Text,
    'driver' : IDL.Opt(IDL.Principal),
  });
  const UserProfile = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FraudAlert = IDL.Record({ 'rideId' : IDL.Nat, 'details' : IDL.Text });
  const DriverProfile = IDL.Record({
    'name' : IDL.Text,
    'earnings' : IDL.Nat,
    'vehicle' : IDL.Text,
    'phone' : IDL.Text,
    'online' : IDL.Bool,
  });
  const PlatformStats = IDL.Record({
    'totalTrips' : IDL.Nat,
    'activeDrivers' : IDL.Nat,
    'fraudAlerts' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRide' : IDL.Func([IDL.Nat], [], []),
    'addFraudAlert' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addMaintenanceAlert' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDriverToVehicle' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'bookRide' : IDL.Func(
        [IDL.Text, IDL.Text, TripType, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getActiveTrips' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'getAllMaintenanceAlerts' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceAlert)],
        ['query'],
      ),
    'getAllRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriverEarnings' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getFraudAlerts' : IDL.Func([], [IDL.Vec(FraudAlert)], ['query']),
    'getOnlineDrivers' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getRideById' : IDL.Func([IDL.Nat], [IDL.Opt(Ride)], ['query']),
    'getRidesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Ride)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerDriver' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleOnlineStatus' : IDL.Func([], [], []),
    'updateRideStatus' : IDL.Func([IDL.Nat, RideStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };