/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DriverProfile {
  'name' : string,
  'earnings' : bigint,
  'vehicle' : string,
  'phone' : string,
  'online' : boolean,
}
export interface FraudAlert { 'rideId' : bigint, 'details' : string }
export interface MaintenanceAlert {
  'owner' : Principal,
  'vehicleNumber' : string,
  'issue' : string,
}
export interface PlatformStats {
  'totalTrips' : bigint,
  'activeDrivers' : bigint,
  'fraudAlerts' : bigint,
  'totalRevenue' : bigint,
}
export interface Ride {
  'id' : bigint,
  'status' : RideStatus,
  'destination' : string,
  'tripType' : TripType,
  'fare' : bigint,
  'user' : Principal,
  'pickup' : string,
  'driver' : [] | [Principal],
}
export type RideStatus = { 'requested' : null } |
  { 'cancelled' : null } |
  { 'in_progress' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type TripType = { 'round' : null } |
  { 'oneway' : null };
export interface UserProfile {
  'city' : string,
  'name' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'model' : string,
  'ownerName' : string,
  'owner' : Principal,
  'make' : string,
  'number' : string,
  'driver' : [] | [Principal],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRide' : ActorMethod<[bigint], undefined>,
  'addFraudAlert' : ActorMethod<[bigint, string], undefined>,
  'addMaintenanceAlert' : ActorMethod<[string, string], undefined>,
  'addVehicle' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDriverToVehicle' : ActorMethod<[string, Principal], undefined>,
  'bookRide' : ActorMethod<[string, string, TripType, bigint], bigint>,
  'getActiveTrips' : ActorMethod<[], Array<Ride>>,
  'getAllMaintenanceAlerts' : ActorMethod<[], Array<MaintenanceAlert>>,
  'getAllRides' : ActorMethod<[], Array<Ride>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDriverEarnings' : ActorMethod<[Principal], bigint>,
  'getFraudAlerts' : ActorMethod<[], Array<FraudAlert>>,
  'getOnlineDrivers' : ActorMethod<[], Array<DriverProfile>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getRideById' : ActorMethod<[bigint], [] | [Ride]>,
  'getRidesByUser' : ActorMethod<[Principal], Array<Ride>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerDriver' : ActorMethod<[string, string, string], undefined>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleOnlineStatus' : ActorMethod<[], undefined>,
  'updateRideStatus' : ActorMethod<[bigint, RideStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];